version: "3"
services:
  db-master:
    container_name: mysql-master
    platform: linux/x86_64
    build:
      context: docker/mysql/master/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - "13306:3306"
    volumes:
      - master_vol:/var/lib/mysql
      - ./docker/mysql/master/scripts:/docker-entrypoint-initdb.d
    networks:
      net-app:
        ipv4_address: 172.28.0.2

  db-slave:
    container_name: mysql-slave
    platform: linux/x86_64
    build:
      context: docker/mysql/slave/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - "13307:3306"
    volumes:
      - slave_vol:/var/lib/mysql
      - ./docker/mysql/slave/scripts:/docker-entrypoint-initdb.d
    networks:
      net-app:
        ipv4_address: 172.28.0.3
    depends_on:
      - db-master

  server-1:
    container_name: server-1
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      net-app:
    depends_on:
      - redis-cache
  server-2:
    container_name: server-2
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    networks:
      net-app:
    depends_on:
      - redis-cache
  server-3:
    container_name: server-3
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8080"
    networks:
      net-app:
    depends_on:
      - redis-cache

  redis-session:
    container_name: session
    platform: linux/x86_64
    build:
      context: docker/redis/session
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6379:6379"
    networks:
      net-app:
    depends_on:
      - db-slave
  redis-cache:
    container_name: cache
    platform: linux/x86_64
    build:
      context: docker/redis/cache
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6378:6379"
    networks:
      net-app:
    depends_on:
      - redis-session

  load-balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server-1
      - server-2
      - server-3
    networks:
      net-app:


volumes:
  master_vol:
  slave_vol:

networks:
  net-app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16