version: "3"
services:
  db-master:
    container_name: mysql-master
    build:
      context: docker/mysql/master/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - "13306:3306"
    volumes:
      - master_vol:/var/lib/mysql
      - ./docker/mysql/master/scripts:/docker-entrypoint-initdb.d
    networks:
      net-app:
        ipv4_address: 172.28.0.2

  db-slave:
    container_name: mysql-slave
    build:
      context: docker/mysql/slave/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
    ports:
      - "13307:3306"
    volumes:
      - slave_vol:/var/lib/mysql
      - ./docker/mysql/slave/scripts:/docker-entrypoint-initdb.d
    networks:
      net-app:
        ipv4_address: 172.28.0.3
    depends_on:
      - db-master

volumes:
  master_vol:
  slave_vol:

networks:
  net-app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16